import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// Import local fonts


// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Add Google Fonts in the <head> */}
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Integral+CF&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
      
      ><Navbar/>
        {children}
        <Footer/>
      </body>
      
    </html>
  );
}
